- README.md
- index.js
- lib/fetch_text.js
It is now possible to fetch pages by wikipedia page id in addition to the wikipedia page title.
> added the functionality to fetch wiki pages by wiki page id

- index.js
Remove the same amount of apostrophes in both sides of text not removing the ones in the actual text
> don't remove too much apostrophes

- src/lib/fetch_text.js
Added callback null value when fetch_text.js errors (such as when connectivity is lost).  Previously this crashed the app.
> Added callback null value when fetch_text.js errors

- src/parse/parse_infobox.js
This is about issue #34 
Regex was not working, or I couldn't find good one. So I iterate over the String, added new line before each relevant '|' and only then using regex to capture each key and value. 
If there is any problem I would love to know about it and fix it if possible. I would love any comments.
> fix issue with infobox parsing

- src/parse/parse_infobox.js
- tests/template_tests.js
I've added a test.
There was small problem with the parsing in some cases and I've fixed it.
> added infobox test

- README.md
- src/index.js
- tests/page_tests.js
Because sometimes, you want lists!
> Added option to include lists when parsing sections

- bin/parse.js
- src/index.js
- src/lib/fetch_text.js
- src/parse/index.js
This is my first pr, so I am not sure, that I am doing it right. I will gladly change it to accommodate all the remarks
> Saving page and wikiid

- src/output/latex/sentence.js
- src/output/reveal/sentence.js
- tests/html.test.js
- tests/latex.test.js
- tests/reveal.test.js
Added optimized test cases for export formats
* html
* latex
* reveal
regards,
Bert
> Newline adaptation of test cases - still 14 failing tests due to added test cases

- src/templates/formatting.js
- src/templates/index.js
- src/templates/misc.js
I ran into some issues running `dumpster-dive` on a recent dump of wikipeda. I hadnt seen these issues with older versions of dumpster dive. These changes fix the issues for me. Thanks for a great set of tools!
> Added some checks for corner cases

- src/output/html/section.js
The function was being printed, not run.
It looks like HTML output might have some other bugs in it as well since not much gets printed out (by default), but I unfortunately didn't have time to look into it.
> Fix printing lists in HTML output

- src/section/references.js
I found some orphan xml tags lying around the xml dump result. This should clean those up.
> match and remove xml with properties

- src/document/preProcess/kill_xml.js
This made more sense to me than parsing it as a space. I understand if you'd like to keep it as a space :)
> parse br as newline

- src/templates/parsers/pipeSplit.js
- tests/template.test.js
I learned some stuff here: https://en.wikipedia.org/wiki/Help:Template#Parameters
> support numeric unnamed parameters in pipeSplit for templates

- src/document/preProcess/kill_xml.js
- src/templates/parsers/pipeSplit.js
Otherwise some gallery and timeline components stay in there :(
> match as many characters as necessary inside unknown html markup

- src/document/preProcess/kill_xml.js
also included capital letters and more params in the tag.
> kill non-selfclosing tags if they are not ref tags

- src/table/toHtml.js
Added an additional `<tr>` tag inside `<thead>` to follow html formatting guidelines #163.
> Fix table header in generated html files

- src/templates/geo/coor.js
- src/templates/geo/index.js
- tests/coord.test.js
this pull request will implement parsing:
[Coor title dms](https://nl.wikipedia.org/wiki/Sjabloon:Coor_title_dms)
[Coor title dec](https://nl.wikipedia.org/wiki/Sjabloon:Coor_title_dec)
[Coor dec](https://nl.wikipedia.org/wiki/Sjabloon:Coor_dms)
[Coor dm](https://nl.wikipedia.org/wiki/Sjabloon:Coor_dm)
[Coor dec](https://nl.wikipedia.org/wiki/Sjabloon:Coor_dec)
> add Coor template

- src/01-document/preProcess/index.js
While reading the source code I found these commented code lines, I guess it was forgotten here while debugging
> Remove commented code

- src/templates/money/index.js
- src/templates/parse.js
- src/templates/stockexchange/index.js
- tests/currencies.test.js
- tests/stockexchange.test.js
Hello!
Added parse stock exchange templates and added INRConvert template.
Feedback is welcome!
Thank you!
> Parse stock exchange templates and Added INRConvert template and some currencies

- src/templates/formatting/punctuation.js
- tests/templates-inline.test.js
Hi,
This PR is proposed as a fix for #312. [Here](https://en.wikipedia.org/wiki/Template:Spaced_en_dash) is a reference for the punctuation template I added.
Let me know if you have any feedback!
> Add snd to punctuation templates

- src/templates/_parsers/01-pipe-splitter.js
- tests/infobox.test.js
https://github.com/spencermountain/wtf_wikipedia/issues/247
https://github.com/spencermountain/wtf_wikipedia/issues/249
> Fix issue with nested infoboxes

- src/04-sentence/index.js
- tests/infobox.test.js
https://github.com/spencermountain/wtf_wikipedia/issues/263
> Fix issue with logo parsing

- src/_fetch/_headers.js
- tests/fetch/fetch.test.js
- tests/fetch/inputs.test.js
#384
Should be able to resolve above issue.
> adds support for editable origin header

- src/template/index.js
- src/template/templates/stock-exchanges.js
- tests/stockexchange.test.js
I added the Euronext paris template and I also checked all the others.
I also sorted the templates and added that in a separate commit between euronext paris and the other templates
My IDE also found a spelling error.
> Euronext paris and others

- src/_fetch/index.js
- src/_fetch/parseDoc.js
- src/index.js
- tests/fetch/inputs.test.js
I was looking trough the issues and I saw https://github.com/spencermountain/wtf_wikipedia/issues/418 and I made a fix for it.
The fixes are that now the fetch function always returns a array if the input was an array else if there is only one then we return the document class
i also saw that i dident ajust the fetch function in the index so i also ajusted the parameters over there
> fixed the in- and output of the fetch function

- README.md
The callback wasn't getting called before
> Fix .fetch() example

- src/_fetch/index.js
- src/_fetch/makeUrl.js
This PR solves #456 
I added an if statement to change the origin in the URL if it is provided.
also added some more docs
> change the parameter if defined

- src/01-document/preProcess/kill_xml.js
- src/template/custom/text-and-data/functions.js
Is it in the right place?
how can I decide to which one of `data-only` `text-and-data` and `text-only` a template belongs?
> add `blockquote` template

- src/03-paragraph/Paragraph.js
> fixed singular mapping typos

- plugins/wikis/wikivoyage/templates.js
> Comment "pagebanner" logic in "wtf-plugin-wikivoyage" to eliminate parsing issue

- src/template/custom/text-and-data/dates/_format.js
- src/template/custom/text-and-data/dates/index.js
- tests/integration/date.test.js
https://en.wikipedia.org/wiki/Template:As_of
> Support 'as of' template
