- README.markdown
- fetch_sitematrix.js
- fetch_text.js
- index.js
- package.json
- sitematrix.js
This lets you specify eg enwiktionary as the parameter which is currently called lang
> Add support to from_api for non-wikipedia wikis

- .gitignore
- index.js
After pull, eg, from http://en.wikipedia.org/wiki/Leopard, ugly "{{Gallery" and "{{Taxobox" remained in text. This takes care of that problem.
> removed unwanted "{{Gallery" and "{{Taxobox" from text

- index.js
- package.json
- tests/test.js
@spencermountain Hi! Having access to the [infobox template type](https://en.wikipedia.org/wiki/Template%3AInfobox) in wtf_wikipedia's parsed response is necessary for the project I'm working on, and this PR adds it. I also fixed the tests while I was at it; there were a number of places where it should've been `test.equal()` instead of `test.ok()`.
> Add infobox template parsing

- package.json
I noticed this when wtf_wikipedia wouldn't work at all when I did `require("wtf_wikipedia")`
> Corrected location of the main file

- src/parse/parse_infobox.js
Fixed issue where integers with commas in them were getting truncated because .replace(/,/g) would turn "12,100" into "12undefined100" and parseInt would then spit out 12.
> Fix to integer parsing in infobox

- src/lib/fetch_text.js
When doing a search like
fetch('HUYF%EHJHDAS#', 'en', function(r) { // 'afwiki'
console.log(JSON.stringify(r, null, 2));
});
the callback will never be called because in fetch_text.js, the eval page && page.revisions && page.revisions[0] will not be true.
the code should then callback with null so that apps using this module can act accordinglya
https://github.com/moustachedelait/wtf_wikipedia/compare/master...moustachedelait:callback_bad_results?expand=1
> Hit callback with null for searches that don't lead to anything useful

- src/lib/fetch_text.js
This can even lead to an infinite loop: search A & B will get interpreted as A. The page for A might redirect to A & B for which the new search will repeat the same process. In my case that exact scenario happened for the search "Jonathan Strange & Mr Norrell" (good book!)
> Requests with an ampersand will break the URL. 

- .travis.yml
having a CI allows maintainers to quickly tell if PRs are breaking tests. also, services like [greenkeeper](https://greenkeeper.io) make it easier to keep up with outdated dependencies! please [enable Travis](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/) along with this PR.
furthermore, I'd add a [build status badge](http://shields.io) that indicates the well-being of a lib to new people.
> use Travis CI for continuous integration

- src/lib/fetch_text.js
We saw this error when looking up something in our production app:
```
Cannot read property 'pages' of undefined
TypeError: Cannot read property 'pages' of undefined
at /var/apps/indigo/ic-webapp/node_modules/wtf_wikipedia/src/lib/fetch_text.js:31:33
at Request.callback (/var/apps/indigo/ic-webapp/node_modules/superagent/lib/node/index.js:619:12)
at /var/apps/indigo/ic-webapp/node_modules/superagent/lib/node/index.js:795:18
at Stream.<anonymous> (/var/apps/indigo/ic-webapp/node_modules/superagent/lib/node/parsers/json.js:16:7)
at emitNone (events.js:86:13)
at Stream.emit (events.js:185:7)
at Unzip.<anonymous> (/var/apps/indigo/ic-webapp/node_modules/superagent/lib/node/utils.js:112:12)
at emitNone (events.js:91:20)
at Unzip.emit (events.js:185:7)
```
Unfortunately because it's in a …
> Catch error: Cannot read property 'pages' of undefined

- src/parse/recursive/index.js
Some MediaWikis contain two or more infoboxes. With the current implementation, only the first of those is parsed and the others discarded. All I did was move the infoboxes into an array, and put the template onto the infobox object itself rather than it's own key.
And example of a MediaWiki with multiple infoboxes is http://oldschoolrunescape.wikia.com/wiki/Amulet_of_magic_(t)?action=raw
> Support multiple infoboxes

- src/lib/fetch_text.js
Just a check that the revisions request response has a body and query field before attempting to access 'pages' field to prevent `Uncaught Exception:  Cannot read property 'pages' of undefined` errors.
> Check revisions response is defined before using

- src/parse/section/image/index.js
links that look like [[Cookbook:Casserole|casserole]] are identified as interlanguage links and removed which also removes the word casserole from the text.
> Interlanguage links interfere with wikibook/cookbook links

- src/lib/convertGeo.js
- src/parse/preProcess/coordinates.js
- tests/coord.test.js
The [United Kingdom](https://en.wikipedia.org/wiki/United_Kingdom) coordinates `{{Coord|51|30|N|0|7|W|type:city}}` are parsed as `{lat: 0, lon: 7}` instead of `{lat: 51.5, lon: -0.11667}` because of `!degrees` check.
The [Guadalcanal Campaign](https://en.wikipedia.org/wiki/Guadalcanal_Campaign) coordinates `{{coord|9|26|44|S|160|01|13|E |format=dms |region:SB_type:event |display=title}}` are parsed as `{lat: -9.44556, lon: null}` instead of `{lat: -9.44556, lon: 160.02028}` because the space in `|E |` is not trimmed.
> Fix coordinate parsing

- src/parse/preProcess/kill_xml.js
Try `wikipedia New York City | grep '<ref'`. There are 11 refs left, for instance:
```
"text": "The city's fast pace<ref name=FastPaceNYC1> defines the term ."
```
instead of
```
"text": "The city's fast pace defines the term New York minute.",
```
I’m not sure if there should be a limit at all, but for now I simply tried to double it.
> Increase maximum <ref> length

- src/parse/infobox/infobox.js
The United Kingdom `infoboxes` are full of trash because the collapsible list removal is case sensitive and limited to 1000 characters:
```
"name": {
"text": "{{collapsible list"
},
"titlestyle": {
"text": "background:transparent;line-height:normal;font-weight:normal;font-size:11px;"
},
"{{Infobox |subbox": {
"text": "yes |bodystyle=font-size:76%;font-weight:normal;"
},
"rowclass1": {
"text": "mergedrow |label1=Scots: |data1={{lang|sco|Unitit Kinrick o Great Breetain an Northren Ireland}}",
}
```
> Fix collapsible list case sensitivity and maximum length

- bin/plaintext.js
- src/index.js
- src/parse/index.js
- src/parse/section/image/index.js
- src/parse/section/index.js
This should pass the test, but keeps extra text in cases where the link is not interlanguage.
If this makes the text too verbose, we can add an option such as verbose to toggle it?
Needed for cases where the name-space is cookbook or wikijunior.
> fix for special namespaces like "cookbook" which get their their text dumped for looking like interwiki links

- README.md
- tests/html.test.js
- tests/latex.test.js
- tests/reveal.test.js
- tests/tidy.js
html_tidy and latex_tidy moved to tidy.js and required that in the test.js files
Handling of relative and inter-wiki links updated.
expanding relative links in the export methods is possible but in the options the language ID e.g. "de" and the domain ID (e.g."wikiversity") is necessary to expand the relative links proper.
Export funcitons need the domain and language in options to expand the Links and image urls.
Thank you Spencer
> html_tidy and latex_tidy moved to tidy.js and handling of relative and inter-wiki links 

- src/fetch.js
- tests/fetch.test.js
Bare queries that contain invalid characters (eg 'Taylor%20Swift', which is encoded as 'Taylor%2520Swift') return an object with the 'invalid' property set. This case differs from the one that was already handled for missing pages (the 'missing' property is set).
This PR addresses the invalid character case and also adds tests for both cases.
An example query directly against the API:
https://en.wikipedia.org/w/api.php?action=query&redirects=true&prop=revisions&rvprop=content&maxlag=5&format=json&origin=*&titles=Taylor%2520Swift
> Handle queries with invalid characters.

- src/templates/currencies.js
- src/templates/index.js
- tests/template.test.js
Currency templates were being ignored. Try e.g. parsing the Microsoft Wikipedia page, which results in an incomplete infobox.
This adds support for the currencies templates that I found.
Sorry for the few formatting changes – they were automatically added by prettier. I can add a commit that undoes them if needed.
> Add support for currency templates

- src/image/Image.js
Because of this issue image urls are created wrongly https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/_AppleTV-4th-gen.png/300px-_AppleTV-4th-gen.png
> Fix issue with spaces before and after file name

- src/document/toHtml.js
- src/list/List.js
- tests/html.test.js
I added a doctype string and some additional elements to the html conversion to match the output of the converter with standard html format (#168).
There was also a small bug in the list to html conversion, where the closing tag was missing a `/`. 
The html tests were also updated to reflect those updates.
Let me know if there are any issues with the changes.
Cheers
> Added additional html elements to conversion scripts

- src/infobox/toHtml.js
Minor change to put start and end tags of infobox `thead` into different lines. This follows the formatting used for the other converted tables. Also, lxml seemed to not like the previous format.
> Write start and end tags of thead into separate lines

- src/lib/recursive_match.js
- src/templates/parsers/_getTemplates.js
Two main things:
- in findFlat, skip runs of characters between close and open delimiters
- in find_recursive, remove an if that is always true and avoid
appending characters that will be ignored by the downstream caller
This improved the runtime of my performance harness from ~8s to ~6.6s,
about an ~18% decrease in runtime.
I'm less sure about this change - I'll call out the specific concerns in the PR.
> Miscellaneous performance improvements

- src/fetch.js
- tests/fetch.test.js
Right now in a personal project I'm getting the data first from https://www.mixesdb.com/db/api.php and then feeding it into wtf but I figured a change like this would make it much more concise and could be useful for other people (although I've not actually tested it with other wikis).
Love the project by the way! Saved so much time
> add ability to pass wikiUrl as an option to wtf.fetch to override wikipedia url

- src/_data/i18n.js
wtf great module is this! By the way I needed Japanese support for this, then I added.
References
- https://ja.wikipedia.org/wiki/Help:%E5%90%8D%E5%89%8D%E7%A9%BA%E9%96%93
- https://ja.wikipedia.org/wiki/Wikipedia:%E6%9B%96%E6%98%A7%E3%81%95%E5%9B%9E%E9%81%BF
> Add japanese locale support to i18n.js

- src/02-section/toJson.js
References aren't currently added to the JSON output of a section, and therefore don't show up in the JSON output of the overall document either. This small code additions adds that ability so references can be outputted.
> Add references to JSON output for sections

- src/_fetch/category.js
Just noticed that `.fetch` supports using other MediaWiki urls, but not `.category`.
I needed this for a side project, and tested it using my fork, and it seems to work.
Any reason this was left out?
Thanks! :wave:
> Add support for wikiUrl option in .category

- types/index.d.ts
As far as I can tell, "str" is an optional parameter but in the definition it's required but can be nothing. Should let `.text()` work instead of requiring `.text(undefined)`.
> fix Sentence.text definition

- types/index.d.ts
Hi 👋
The purpose of this PR is to include numbers in the type definition for the fetch method's primary parameter and take into account the fact that IDs can be used to identify pages not just titles.
This is my first PR to the repo. Let me know if you have any feedback!
> Expand type for fetch primary parameter

- src/01-document/disambig.js
Hi,
This PR is proposed as a fix for #313. In particular, the second capturing group (called `allowedCharacters` in the PR) has been modified. Now when a disambiguation keyword is included along with more than one other template keyword (such as in the case `{{disambiguation|geo|surname}}`, it no longer fails the regex test.
Let me know if you have any feedback.
> Make disambiguation regex more permissive

- src/04-sentence/parse.js
- src/_data/abbreviations.js
Hi,
This PR is proposed as a fix for #267. In particular, it modifies the abbreviations regex to prevent the incorrect categorisation of sentences.
Let me know if you have any feedback.
> Make abbreviations regex more restrictive

- src/02-section/table/parse/index.js
- tests/table.test.js
I believe this fixes #332 (all tests pass and added a new one for the specific issue).
I'm not totally in love with the regex approach - however I started by trying to detect this situation and append the current line on to the end of the previous one as we are iterating the lines, but it got messy and this seemed much cleaner.
Note this change doesn't perfectly represent the behavior of the wikipedia parser, because we now respect a `||` in the line after a line break, whereas wikipedia only allows it after a `<br />` and not after a 'manual' newline - but I haven't worried about that because I can't imagine anyone actually _cares_.
> Fixed handling of newlines within table cells. closes #332

- src/_fetch/_request.js
- tests/fetch.test.js
Sets the `User-Agent` header in addition to `Api-User-Agent` when making requests. The wikimedia docs are unclear on the difference, but my testing shows that the latter is not sufficient if you're also setting a common `User-Agent` header (which was the case here, as it defaulted to the header set by the `fetch` library).
This changes allows `User-Agent` and `Api-User-Agent` to be set independently, however for backwards compatability if your config has `Api-User-Agent` but not `User-Agent` then the value from `Api-User-Agent` will be copied to the `User-Agent` header.
Fixes #334.
> Allowing the User-Agent header to be set

- package.json
This requires sh (or bash), so it likely won't work on Windows.
> on `npm install`, also run `npm install` in all plugin directories; fixes #368

- src/template/templates/science.js
- tests/templates-data.test.js
Because of changes to the `data` format, some items would end up in the
wrong attributes. The new row parsing implementation accommodates these
changes and now mimics the template's Lua code.
This commit also renames the `rows` attribute to `data` to match the
template syntax, adds an `options` attribute for named arguments like
`alttot1`, and changes all attribute names to camelCase.
> update Template:Medical_cases_chart parsing for new `data` format

- src/link/interwiki.js
- tests/interwiki.test.js
Resolves #378
There are still some edge cases (especially the ones where wiki vs language vs namespace is ambiguous) that are trickier to handle, but this is good to begin with.
> Add support for complex interwiki links

- package.json
- src/man/wtf_wikipedia.1
Added in a man page for `wtf_wikipedia`.
Here is a list of updates
* Edited `package.json` to include an entry called `man` (`npm` automatically installs man pages inside the `man` entry)
* Created a file at `src/man/wtf_wikipedia`
* Added in a man page at `src/man/wtf_wikipedia`
To test the layout, run:
```bash
git clone https://github.com/Yash-Singh1/wtf_wikipedia.git
cd wtf_wikipedia/src/man
man ./wtf_wikipedia.1
```
To test the changes, run:
```bash
git clone https://github.com/Yash-Singh1/wtf_wikipedia.git
cd wtf_wikipedia
sudo npm -g uninstall wtf_wikipedia ; npm link
```
Run `man wtf_wikipedia` and the manual page should appear.
To go back to the normal environment:
```bash
sudo npm -g uninstall wtf_wikipedia ; npm -g install wtf_wikipedia
```
***Note: The testing process will only …
> Added man page for wtf_wikipedia

- package-lock.json
- package.json
If you don't like external packages in critical places, then this PR is a doozy.
There are two big changes and a small one:
I used [cross-env](https://www.npmjs.com/package/cross-env) to set the env variables on all platforms. the current implementation does not work on windows.
and then I replaced the prepare with a postInstall. this is a small change if you don't expect to run this command at build time.
And because there are no normal dependencies, I think that we are ok in that regard
and then I replaced the for loop with [npm-recursive-install](https://www.npmjs.com/package/recursive-install). it is not a widely used package. but it is small enough that you can understand all the source code and see that it does not do anything weird.
And lastly, I sorted the scripts in alphabetical …
> Add windows compatibility

- README.md
Links to build files in readme weren't correct, simply fixed them.
> Fixed links to builds

- types/index.d.ts
Typescript 4.4.4 reports:
```
Error: node_modules/wtf_wikipedia/types/index.d.ts:215:10 - error TS2749: 'fetch' refers to a value, but is being used as a type here. Did you mean 'typeof fetch'?
```
> Typescript 4.4: Refer to typeof fetch, not the value fetch

- plugins/person/README.md
- plugins/person/src/parseDate.js
Added more checks for inaccurate dates. for ranges returns the average rounded down, otherwise the minimum.
For inaccurate dates adds the non-enumerable `.originalDate` property to the result.
For dates up to the second millennium tricks spacetime to get the right result.
If parsing was unsuccessful (`{ year: 1970, month: 0, date: 1 }`), returns null.
> add more checks

- src/link/interwiki.js
- tests/integration/interwiki.test.js
#379 introduced a bug where `[[some text: more text: even more text]]` (as seen in the wild [here](https://starwars.fandom.com/wiki/Starlight:_Part_One:_Go_Together)) gets interpreted as an interwiki link when it shouldn't.
> fixed interwiki parsing bug and added tests

- src/table/parse/_findRows.js
- src/table/parse/index.js
- tests/integration/table.test.js
This fixes two bugs.
First was incorrectly parsing multiple pipes in a cell: `| styling | content | more content, the pipe is just part of the content`. The greedy regex would eat everything until the last pipe instead of just up to the first one
Second bug was the parsing of `|||` at the start of line which is basically an empty cell, but the parser would skip it so if we had:
```
column1  | column2
| cell2
```
cell2 would be parsed as part of column1 instead of column2.
Also should this be 2 separate PRs or is this fine?
> fixed table parsing bugs

- src/image/Image.js
- src/image/index.js
- src/infobox/Infobox.js
`Image` is used in several places and some of them like [here](https://github.com/spencermountain/wtf_wikipedia/blob/e702419c8ac8bb2b16965a46e3ac3b52b218ddcf/src/01-document/Document.js#L326) lack this piece of code so I moved the code to `Image.js` and deleted the rest
> refactor: move `file()`-related code to `Image.js`

- plugins/api/src/getCategory.js
When `getCategory` was called, `options` were ignored and `defaults` were used.
> Fix getCategory always using default options

- README.md
- plugins/api/README.md
- plugins/api/src/getCategory.js
- plugins/api/tests/category.test.js
From the doc changes it looks like I'm significantly changing the API - I'm not, I'm just changing the doc to what the code currently does (or at least, as far as I can tell).
Note for these changes to work locally required #522, for me at least.
Closes #521.
> getCategoryPages now returns subcategories

- plugins/api/README.md
- plugins/api/src/getCategory.js
- plugins/api/tests/category.test.js
> Adding a depth parameter to getCategory

- package-lock.json
- plugins/markdown/src/01-doc.js
- plugins/markdown/tests/markdown.test.js
Fixes a bug where ``.markdown({references: true})`` would output:
```md
[object Object]
```
Fix was moving from .json to .markdown
> Make references output correctly in markdown

- src/_fetch/index.js
This PR will NOW close issue [#246](https://github.com/spencermountain/wtf_wikipedia/issues/547).
Throwing / handling this error. 
```js
Un-handled Errors:
/node_modules/wtf_wikipedia/src/_fetch/index.js:71:18
TypeError: Cannot convert undefined or null to object
```
Same as before, but should pass build testing :blush: - *my bad*.
> Fix for invalid JSON data :hammer:

- src/01-document/Document.js
- tests/integration/Document.test.js
This change adds initial support for revisionID as passed in through options. This is useful because one can use this to check for revision changes between two wikipedia dumps, like when using dumpster-dip on a monthly basis to keep a search database up-to-date (for RAG for example).
Mostly I just missed having this, and I plan to submit a follow-up PR to dumpster-dip to have it parse the revisionID and pass it in so I can use it.
Note that this change does not include updating the README and types yet, I will do that, but I wanted to wait for feedback on naming etc. first.
> Add support for revisionID

- src/_data/flags.js
```
🏴 WAVING BLACK FLAG
󠁧 TAG LATIN SMALL LETTER G
󠁢 TAG LATIN SMALL LETTER B
󠁥 TAG LATIN SMALL LETTER E
󠁮 TAG LATIN SMALL LETTER N
󠁧 TAG LATIN SMALL LETTER G
󠁿 CANCEL TAG
󠁧 TAG LATIN SMALL LETTER G
󠁢 TAG LATIN SMALL LETTER B
󠁥 TAG LATIN SMALL LETTER E
󠁮 TAG LATIN SMALL LETTER N
󠁧 TAG LATIN SMALL LETTER G
󠁿 CANCEL TAG
```
to 
```
🏴 WAVING BLACK FLAG
󠁧 TAG LATIN SMALL LETTER G
󠁢 TAG LATIN SMALL LETTER B
󠁥 TAG LATIN SMALL LETTER E
󠁮 TAG LATIN SMALL LETTER N
󠁧 TAG LATIN SMALL LETTER G
󠁿 CANCEL TAG
󠁧```
> Fix incorrect representation of English flag

- README.md
Small PR - Commit 4764de1e0263e6945c51c36bcb97acbcac77320f renamed `builds/wtf_wikipedia.js`  to be `builds/wtf_wikipedia.cjs`. This PR adjusts `README.md` to changes and fixes a few typos on the way.
> update `wtf_wikipedia.cjs` reference
